-- Renewal pipeline operational management
-- Adds owner assignment, next action and change history

ALTER TABLE renewal_alerts_state
  ADD COLUMN IF NOT EXISTS assigned_to text,
  ADD COLUMN IF NOT EXISTS next_action text;

CREATE TABLE IF NOT EXISTS renewal_alerts_history (
  id bigint generated by default as identity primary key,
  alert_key text NOT NULL,
  policy_id text REFERENCES policies(id),
  previous_status text,
  new_status text NOT NULL,
  previous_assigned_to text,
  new_assigned_to text,
  previous_next_action text,
  new_next_action text,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS renewal_alerts_history_alert_key_idx
  ON renewal_alerts_history (alert_key);

CREATE INDEX IF NOT EXISTS renewal_alerts_history_changed_at_idx
  ON renewal_alerts_history (changed_at DESC);
