/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as QuotesComparisonRouteImport } from './routes/quotes-comparison'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PartnerRiskRouteImport } from './routes/partner-risk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OneIndexRouteImport } from './routes/one/index'
import { Route as OneTermsRouteImport } from './routes/one/terms'
import { Route as OneResetPasswordRouteImport } from './routes/one/reset-password'
import { Route as OneProfileRouteImport } from './routes/one/profile'
import { Route as OnePoliciesRouteImport } from './routes/one/policies'
import { Route as OneLoginRouteImport } from './routes/one/login'
import { Route as OneDocumentsRouteImport } from './routes/one/documents'
import { Route as OneDashboardRouteImport } from './routes/one/dashboard'
import { Route as OneClaimsRouteImport } from './routes/one/claims'
import { Route as AdminCarrierIntegrationsRouteImport } from './routes/admin.carrier-integrations'
import { Route as AdminCarrierIntegrationsRunsIdRouteImport } from './routes/admin.carrier-integrations.runs.$id'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesComparisonRoute = QuotesComparisonRouteImport.update({
  id: '/quotes-comparison',
  path: '/quotes-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRiskRoute = PartnerRiskRouteImport.update({
  id: '/partner-risk',
  path: '/partner-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OneIndexRoute = OneIndexRouteImport.update({
  id: '/one/',
  path: '/one/',
  getParentRoute: () => rootRouteImport,
} as any)
const OneTermsRoute = OneTermsRouteImport.update({
  id: '/one/terms',
  path: '/one/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OneResetPasswordRoute = OneResetPasswordRouteImport.update({
  id: '/one/reset-password',
  path: '/one/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OneProfileRoute = OneProfileRouteImport.update({
  id: '/one/profile',
  path: '/one/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnePoliciesRoute = OnePoliciesRouteImport.update({
  id: '/one/policies',
  path: '/one/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OneLoginRoute = OneLoginRouteImport.update({
  id: '/one/login',
  path: '/one/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OneDocumentsRoute = OneDocumentsRouteImport.update({
  id: '/one/documents',
  path: '/one/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OneDashboardRoute = OneDashboardRouteImport.update({
  id: '/one/dashboard',
  path: '/one/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OneClaimsRoute = OneClaimsRouteImport.update({
  id: '/one/claims',
  path: '/one/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarrierIntegrationsRoute =
  AdminCarrierIntegrationsRouteImport.update({
    id: '/carrier-integrations',
    path: '/carrier-integrations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCarrierIntegrationsRunsIdRoute =
  AdminCarrierIntegrationsRunsIdRouteImport.update({
    id: '/runs/$id',
    path: '/runs/$id',
    getParentRoute: () => AdminCarrierIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/partner-risk': typeof PartnerRiskRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/quotes-comparison': typeof QuotesComparisonRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/carrier-integrations': typeof AdminCarrierIntegrationsRouteWithChildren
  '/one/claims': typeof OneClaimsRoute
  '/one/dashboard': typeof OneDashboardRoute
  '/one/documents': typeof OneDocumentsRoute
  '/one/login': typeof OneLoginRoute
  '/one/policies': typeof OnePoliciesRoute
  '/one/profile': typeof OneProfileRoute
  '/one/reset-password': typeof OneResetPasswordRoute
  '/one/terms': typeof OneTermsRoute
  '/one/': typeof OneIndexRoute
  '/admin/carrier-integrations/runs/$id': typeof AdminCarrierIntegrationsRunsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/partner-risk': typeof PartnerRiskRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/quotes-comparison': typeof QuotesComparisonRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/carrier-integrations': typeof AdminCarrierIntegrationsRouteWithChildren
  '/one/claims': typeof OneClaimsRoute
  '/one/dashboard': typeof OneDashboardRoute
  '/one/documents': typeof OneDocumentsRoute
  '/one/login': typeof OneLoginRoute
  '/one/policies': typeof OnePoliciesRoute
  '/one/profile': typeof OneProfileRoute
  '/one/reset-password': typeof OneResetPasswordRoute
  '/one/terms': typeof OneTermsRoute
  '/one': typeof OneIndexRoute
  '/admin/carrier-integrations/runs/$id': typeof AdminCarrierIntegrationsRunsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/partner-risk': typeof PartnerRiskRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/quotes-comparison': typeof QuotesComparisonRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/carrier-integrations': typeof AdminCarrierIntegrationsRouteWithChildren
  '/one/claims': typeof OneClaimsRoute
  '/one/dashboard': typeof OneDashboardRoute
  '/one/documents': typeof OneDocumentsRoute
  '/one/login': typeof OneLoginRoute
  '/one/policies': typeof OnePoliciesRoute
  '/one/profile': typeof OneProfileRoute
  '/one/reset-password': typeof OneResetPasswordRoute
  '/one/terms': typeof OneTermsRoute
  '/one/': typeof OneIndexRoute
  '/admin/carrier-integrations/runs/$id': typeof AdminCarrierIntegrationsRunsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/claims'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/partner-risk'
    | '/policies'
    | '/privacy-policy'
    | '/profile'
    | '/quotes-comparison'
    | '/terms-and-conditions'
    | '/admin/carrier-integrations'
    | '/one/claims'
    | '/one/dashboard'
    | '/one/documents'
    | '/one/login'
    | '/one/policies'
    | '/one/profile'
    | '/one/reset-password'
    | '/one/terms'
    | '/one/'
    | '/admin/carrier-integrations/runs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/claims'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/partner-risk'
    | '/policies'
    | '/privacy-policy'
    | '/profile'
    | '/quotes-comparison'
    | '/terms-and-conditions'
    | '/admin/carrier-integrations'
    | '/one/claims'
    | '/one/dashboard'
    | '/one/documents'
    | '/one/login'
    | '/one/policies'
    | '/one/profile'
    | '/one/reset-password'
    | '/one/terms'
    | '/one'
    | '/admin/carrier-integrations/runs/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/claims'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/partner-risk'
    | '/policies'
    | '/privacy-policy'
    | '/profile'
    | '/quotes-comparison'
    | '/terms-and-conditions'
    | '/admin/carrier-integrations'
    | '/one/claims'
    | '/one/dashboard'
    | '/one/documents'
    | '/one/login'
    | '/one/policies'
    | '/one/profile'
    | '/one/reset-password'
    | '/one/terms'
    | '/one/'
    | '/admin/carrier-integrations/runs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  ClaimsRoute: typeof ClaimsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PartnerRiskRoute: typeof PartnerRiskRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  QuotesComparisonRoute: typeof QuotesComparisonRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  OneClaimsRoute: typeof OneClaimsRoute
  OneDashboardRoute: typeof OneDashboardRoute
  OneDocumentsRoute: typeof OneDocumentsRoute
  OneLoginRoute: typeof OneLoginRoute
  OnePoliciesRoute: typeof OnePoliciesRoute
  OneProfileRoute: typeof OneProfileRoute
  OneResetPasswordRoute: typeof OneResetPasswordRoute
  OneTermsRoute: typeof OneTermsRoute
  OneIndexRoute: typeof OneIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes-comparison': {
      id: '/quotes-comparison'
      path: '/quotes-comparison'
      fullPath: '/quotes-comparison'
      preLoaderRoute: typeof QuotesComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-risk': {
      id: '/partner-risk'
      path: '/partner-risk'
      fullPath: '/partner-risk'
      preLoaderRoute: typeof PartnerRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/': {
      id: '/one/'
      path: '/one'
      fullPath: '/one/'
      preLoaderRoute: typeof OneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/terms': {
      id: '/one/terms'
      path: '/one/terms'
      fullPath: '/one/terms'
      preLoaderRoute: typeof OneTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/reset-password': {
      id: '/one/reset-password'
      path: '/one/reset-password'
      fullPath: '/one/reset-password'
      preLoaderRoute: typeof OneResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/profile': {
      id: '/one/profile'
      path: '/one/profile'
      fullPath: '/one/profile'
      preLoaderRoute: typeof OneProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/policies': {
      id: '/one/policies'
      path: '/one/policies'
      fullPath: '/one/policies'
      preLoaderRoute: typeof OnePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/login': {
      id: '/one/login'
      path: '/one/login'
      fullPath: '/one/login'
      preLoaderRoute: typeof OneLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/documents': {
      id: '/one/documents'
      path: '/one/documents'
      fullPath: '/one/documents'
      preLoaderRoute: typeof OneDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/dashboard': {
      id: '/one/dashboard'
      path: '/one/dashboard'
      fullPath: '/one/dashboard'
      preLoaderRoute: typeof OneDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/claims': {
      id: '/one/claims'
      path: '/one/claims'
      fullPath: '/one/claims'
      preLoaderRoute: typeof OneClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/carrier-integrations': {
      id: '/admin/carrier-integrations'
      path: '/carrier-integrations'
      fullPath: '/admin/carrier-integrations'
      preLoaderRoute: typeof AdminCarrierIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carrier-integrations/runs/$id': {
      id: '/admin/carrier-integrations/runs/$id'
      path: '/runs/$id'
      fullPath: '/admin/carrier-integrations/runs/$id'
      preLoaderRoute: typeof AdminCarrierIntegrationsRunsIdRouteImport
      parentRoute: typeof AdminCarrierIntegrationsRoute
    }
  }
}

interface AdminCarrierIntegrationsRouteChildren {
  AdminCarrierIntegrationsRunsIdRoute: typeof AdminCarrierIntegrationsRunsIdRoute
}

const AdminCarrierIntegrationsRouteChildren: AdminCarrierIntegrationsRouteChildren =
  {
    AdminCarrierIntegrationsRunsIdRoute: AdminCarrierIntegrationsRunsIdRoute,
  }

const AdminCarrierIntegrationsRouteWithChildren =
  AdminCarrierIntegrationsRoute._addFileChildren(
    AdminCarrierIntegrationsRouteChildren,
  )

interface AdminRouteChildren {
  AdminCarrierIntegrationsRoute: typeof AdminCarrierIntegrationsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCarrierIntegrationsRoute: AdminCarrierIntegrationsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  ClaimsRoute: ClaimsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PartnerRiskRoute: PartnerRiskRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  QuotesComparisonRoute: QuotesComparisonRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  OneClaimsRoute: OneClaimsRoute,
  OneDashboardRoute: OneDashboardRoute,
  OneDocumentsRoute: OneDocumentsRoute,
  OneLoginRoute: OneLoginRoute,
  OnePoliciesRoute: OnePoliciesRoute,
  OneProfileRoute: OneProfileRoute,
  OneResetPasswordRoute: OneResetPasswordRoute,
  OneTermsRoute: OneTermsRoute,
  OneIndexRoute: OneIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
